title: Less is more.
name: ArchieYao
user_description: Programmer.
notes_url: "https://archieyao.github.io/"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.ico
copyright_name: archieyao.github.io/
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://archieyao.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jemoji
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

comments: true

# Gitalk settings
comment_gitalk_clientId: c1c0a0d0a6757f360ba9
comment_gitalk_clientSecret: 029e259d1670eb63283fbe755e58592f35975fc8
comment_gitalk_repo: GithubPages-comment
github_username: ArchieYao

#disqus:
#  comments: true  # boolean type, the global switch for posts comments.
#  shortname: 'archieyao-github-io'    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
