# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 20 # pagination based on number of posts
paginate_path: "page:num"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
highlighter: rouge
markdown: kramdown
disqus: yaoqi17
#google_analytics: darren987469
title: yaoqi17.github.io
layout: default
comments: true
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: yaoqi17.github.io

description: Stylish Jekyll Theme
author:
  name: YaoQi
  email: 168412217.mail@gmail.com
  github: yaoqi17
  #twitter:
  #pinterest:
  #linkedin: darren987469
  bio: Stary foolish.
  email_md5:

rss_path: feed.xml
categories_path: categories
# tags_path: tags
contributions_path: contributions
about_path: about
date_format: '%Y/%m/%d'

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

permalink: /:title/
plugins:
  - jekyll-paginate
